# Pre-commit hooks for Python deep learning project
repos:
  # Basic file hygiene and Python checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace  # Removes trailing whitespace
      - id: end-of-file-fixer   # Ensures files end with a newline
      - id: check-yaml          # Validates YAML syntax (important for config files)
      - id: check-added-large-files  # Prevents large data files from being committed
      - id: check-ast          # Checks Python syntax
      - id: debug-statements   # Checks for debugger imports and py37+ breakpoint() calls
      - id: requirements-txt-fixer  # Sorts requirements.txt

  # Python code formatting with Black
  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black
        language_version: python3
        args: ["--line-length=150"]

  # Import sorting with isort (configured to be compatible with Black)
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: [
          "--profile", "black",
          "--line-length=150",  # Match Black's line length
          "--multi-line=3",
          "--force-grid-wrap=0",
        ]
        files: "\\.(py)$"

  # Flake8 for Python code analysis
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: [
          "--max-line-length=120",  # Match Black's line length
          "--extend-ignore=E203,E402,F401,F541,F601,E713,F841,E722",  # Ignore specific issues
          "--per-file-ignores=__init__.py:F401",
        ]
